apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.0'
    }
}

android {
    compileSdkVersion 35
    buildToolsVersion '36.0.0'

    defaultConfig {
        minSdkVersion 28
        targetSdkVersion 35
    }

    sourceSets.main {
        manifest.srcFile 'library/src/main/AndroidManifest.xml'
        java.srcDirs = ['library/src/main/java']
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    namespace 'com.tokenautocomplete'
}

task jar(type: Jar) {
    dependsOn "assembleRelease"
    from fileTree(dir: 'build/classes/release')
}
